name: Azure ML Pipeline Setup

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GROUP: mlops-project
  WORKSPACE: sadiksha-sapkota-ml
  LOCATION: westeurope
  COMPUTE_NAME: cli-created-machine-v2

jobs:
  setup-compute:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Azure -- Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🛠 Install Azure CLI + ML extension
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add --name ml -y
          az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION

      - name: ⚙️ Azure -- Create compute if not exists
        run: |
          echo "Checking if compute '$COMPUTE_NAME' exists..."
          if ! az ml compute show --name $COMPUTE_NAME > /dev/null 2>&1; then
            echo "Compute not found — creating..."
            az ml compute create --file ./environment/compute.yaml
          else
            echo "✅ Compute already exists. Skipping creation."
          fi

      - name: 🚀 Azure -- Start Compute (only if stopped)
        run: |
          echo "Checking compute status..."
          sleep 5  # Add delay to allow proper context after login

          STATUS=$(az ml compute show --name $COMPUTE_NAME --query "status.state" -o tsv 2>/dev/null || echo "Unknown")
          echo "Current status: '$STATUS'"

          if [[ "$STATUS" == "Stopped" ]]; then
            echo "Compute is stopped. Attempting to start..."
            az ml compute start --name $COMPUTE_NAME || echo "⚠️ Start failed. Ignoring..."
          elif [[ "$STATUS" == "Running" ]]; then
            echo "✅ Compute is already running. No need to start."
          elif [[ "$STATUS" == "Unknown" || -z "$STATUS" ]]; then
            echo "⚠️ Could not detect compute status properly. Continuing anyway..."
          else
            echo "⚠️ Skipping start: Compute is in status '$STATUS'."
          fi
        continue-on-error: true


      - name: 🧪 Azure -- Register Environments
        run: |
          az ml environment create --file ./environment/pillow.yaml
          az ml environment create --file ./environment/tensorflow.yaml

      - name: 🧩 Azure -- Register Components
        run: |
          az ml component create --file ./components/components/dataprep/dataprep.yaml
          az ml component create --file ./components/components/dataprep/data_split.yaml
          az ml component create --file ./components/components/training/training.yaml

      - name: 📦 Azure -- Submit MNIST Training Pipeline
        run: |
          az ml job create \
            --file ./pipeline/pipeline.yaml \
            --stream \
            --set name=mnist-pipeline-${{ github.sha }}-${{ github.run_id }}
