$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

name: mnist-training-pipeline-v12
display_name: MNIST Full Preprocessing & Training
experiment_name: mnist-training
type: pipeline

inputs:
  train_test_split_factor: 20
  epochs: 20

  mnist_2_raw:
    type: uri_folder
    path: azureml:mnist-2:1
  mnist_7_raw:
    type: uri_folder
    path: azureml:mnist-7:1
  mnist_8_raw:
    type: uri_folder
    path: azureml:mnist-8:1

outputs:
  model:
    type: uri_folder

settings:
  default_compute: azureml:cli-created-machine-v2

jobs:

  resize_mnist_2:
    type: command
    component: azureml:dataprep_mnist_jpg_converter:0.1.1
    inputs:
      data: ${{parent.inputs.mnist_2_raw}}
    outputs:
      output_data:
        mode: rw_mount

  resize_mnist_7:
    type: command
    component: azureml:dataprep_mnist_jpg_converter:0.1.1
    inputs:
      data: ${{parent.inputs.mnist_7_raw}}
    outputs:
      output_data:
        mode: rw_mount

  resize_mnist_8:
    type: command
    component: azureml:dataprep_mnist_jpg_converter:0.1.1
    inputs:
      data: ${{parent.inputs.mnist_8_raw}}
    outputs:
      output_data:
        mode: rw_mount

  split:
    type: command
    component: azureml:data_split_mnist_cli:0.1.1
    inputs:
      mnist_2: ${{parent.jobs.resize_mnist_2.outputs.output_data}}
      mnist_7: ${{parent.jobs.resize_mnist_7.outputs.output_data}}
      mnist_8: ${{parent.jobs.resize_mnist_8.outputs.output_data}}
      train_test_split_factor: ${{parent.inputs.train_test_split_factor}}
    outputs:
      training_data:
        mode: rw_mount
      testing_data:
        mode: rw_mount

  training:
    type: command
    component: azureml:training_mnist_cli:0.1.0
    inputs:
      training_folder: ${{parent.jobs.split.outputs.training_data}}
      testing_folder: ${{parent.jobs.split.outputs.testing_data}}
      epochs: ${{parent.inputs.epochs}}
    outputs:
      output_folder:
        mode: rw_mount

  register:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.9
    inputs:
      model_name: mnist-classifier
      model_type: custom_model
      model_path: ${{parent.jobs.training.outputs.output_folder}}
    outputs:
      registration_details_folder: ${{parent.outputs.model}}
